spring:
  application:
    name: LeverX-final-project
  datasource:
    url: ${LEVERX_FINAL_PROJECT_DB_URL}
    username: ${LEVERX_FINAL_PROJECT_USER}
    password: ${LEVERX_FINAL_PROJECT_PASSWORD}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  mail:
    host: smtp.gmail.com
    port: 587
    username: ${DESIGN-SERVICE-EMAIL}
    password: ${DESIGN-SERVICE-APP-PASSWORD}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
  data:
    redis:
      host: localhost
      port: 6379
      database: 0
      connect-timeout: 2000


jwt:
  secret-key: ${JAVA_COURSE_JWT_KEY}